/**
 * Calculate carbon credits generated by a project.
 *
 * Methodology based on IPCC 2023 guidelines:
 *   - tree_plantation:    (treesPlanted × 0.02) + (landArea × 0.5)  credits/year
 *   - soil_carbon:        landArea × 1.2  credits
 *   - renewable_energy:   landArea × 2.0  credits
 *
 * @param {{ treesPlanted: number, landArea: number, projectType: string }} params
 * @returns {{ credits: number, co2Saved: number, methodology: string }}
 */
export function calculateCredits({ treesPlanted = 0, landArea = 0, projectType }) {
  let credits = 0;

  switch (projectType) {
    case "tree_plantation":
      credits = treesPlanted * 0.02 + landArea * 0.5;
      break;
    case "soil_carbon":
      credits = landArea * 1.2;
      break;
    case "renewable_energy":
      credits = landArea * 2.0;
      break;
    default:
      credits = 0;
  }

  credits = Math.round(credits * 100) / 100;

  return {
    credits,
    co2Saved: Math.round(credits * 1000 * 100) / 100, // kg
    methodology: "IPCC 2023 Standard",
  };
}
